from time import sleep
from colorama import Fore
import imports.own.will_go_to_start

def commands_start():
    
            print(Fore.RED + "\n" + "COMMANDS:") # !MAIN COMMANDS!
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "MAINS:") # class MAINS: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "--help " + Fore.CYAN + "or " + Fore.WHITE + "-help " + Fore.CYAN + "or " + Fore.WHITE + "help " + Fore.CYAN + "or " + Fore.WHITE + "-h" + " - shows all commands ") # --help (+)
            sleep(0.01)
            print("--version " + Fore.CYAN + "or " + Fore.WHITE + "-version " + Fore.CYAN + "or " + Fore.WHITE + "version " + Fore.CYAN + "or " + Fore.WHITE + "-v" + " - shows version ") # --version (+)
            sleep(0.01)
            print("pip - using pip commands") # pip (+)
            sleep(0.01)
            print("git - using git commands") # git (+)
            sleep(0.01)
            print("conda - using conda commands") # conda (+)
            sleep(0.01)
            print("cmd - using cmd commands") # cmd (+)
            sleep(0.01)
            print("cls " + Fore.CYAN + "or " + Fore.WHITE + "clear" + " - clear your screen ") # cls (+)
            sleep(0.01)
            print("go_to - go to entered directory " + Fore.YELLOW + "( " + Fore.WHITE + "path" + Fore.YELLOW + " )" + Fore.WHITE) # go_to (+)
            sleep(0.01)
            print("dir " + Fore.CYAN + "or " + Fore.WHITE + "ls" + " - shows all files of current directory ") # dir (+)
            sleep(0.01)
            print("mkdir - create new folder with entered name " + Fore.YELLOW + "( " + Fore.WHITE + "folder name" + Fore.YELLOW + " )" + Fore.WHITE) # mkdir (+)
            sleep(0.01)
            print("create - create new file with entered name.type " + Fore.YELLOW + "( " + Fore.WHITE + "name.type" + Fore.YELLOW + " )" + Fore.WHITE) # create (+)
            sleep(0.01)
            print("del " + Fore.CYAN + "or " + Fore.WHITE + "delete" + " - delete entered file " + Fore.YELLOW + "( " + Fore.WHITE + "file name" + Fore.YELLOW + " )" + Fore.WHITE) # del (+)
            sleep(0.01)
            print("install - install entered option \033[0;33m(\033[0;37m 7-zip, google_chrome, git, miniconda, python-3.10.6, torrent, virtualbox,\n                                   visual_studio, vlc, vscode, winsdk, wireshark, zeal, zoom, blue_stacks,\n                                   steam, unity, epic_games, custom_cursor, skype, viber, telegram, npm \033[0;33m)\n" + Fore.WHITE) # install (+)
            sleep(0.01)
            print("update - update Dragon console to last version") # update (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "HACKER STUFFS:") # class HACKER STUFFS: (+)
            sleep(0.01)
            print(" ")
            print(Fore.WHITE + "inject_prog - shows injector for any program") # inject_prog (+)
            sleep(0.01)
            print("pas_gen - shows password generator " + Fore.YELLOW + "(" + Fore.WHITE + " w, u, n, nw " + Fore.YELLOW + ")" + Fore.WHITE) # pas_gen (+)
            sleep(0.01)
            print("my_wifi_pas - shows list passwords of yours wifi") # my_wifi_pas (+)
            sleep(0.01)
            print("cor_desk - shows coordinates Desktop screen") # cor_desk (+)
            sleep(0.01)
            print("ascii_code - shows ascii code keybord") # ascii_code (+)
            sleep(0.01)
            print("ip_search - searching location by entered network ip address (for location on google maps use (https://www.maps.ie/coordinates.html))") # ip_search (+)
            sleep(0.01)
            print("phone_search - searching location by entered phone number with country code (for location on google maps use (https://www.maps.ie/coordinates.html))") # phone_search (+)
            sleep(0.01)
            print("mimikatz - open mimikatz prog") # mimikatz (+)
            sleep(0.01)
            print("john_the_ripper - open john_the_ripper prog") # john_the_ripper (+)
            sleep(0.01)
            print("con_wifi - doing connection to entered wifi") # con_wifi (+)
            sleep(0.01)
            print("wifi_hack - shows tool for hacking wifi password") # wifi_hack (+) 
            sleep(0.01)
            #print("stealer - copy importent files windows in target_files_dis folder") # stealer (+) 
            #sleep(0.01)
            print("get_ip_website - shows ip address entered site " + Fore.YELLOW + "( " + Fore.WHITE + "website name" + Fore.YELLOW + " )" + Fore.WHITE) # get_ip_website (+)
            sleep(0.01)
            print("auto_clicker - auto clicking, for exit press 'Esc'") # auto_clicker (+)
            sleep(0.01)
            print("morse_code - shows morse code cipher") # morse_code (+)
            sleep(0.01)
            print("caesar_cipher - shows caesar cipher") # caesar_cipher (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "PICTURES:") # class PICTURES: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "ukraine - shows flag Ukraine") # ukraine (+)
            sleep(0.01)
            print("author - shows author of this console") # author (+)
            sleep(0.01)
            print("matrix - shows hacker matrix") # matrix (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "ACCOUNTS:") # class ACCOUNTS: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "login - go to login page") # login (+)
            sleep(0.01)
            print("registration - go to registration page") # registration (+)
            sleep(0.01)
            print("instructions - go to instructions page") # instructions (+)
            sleep(0.01)
            print("del_account - delete entered account") # del_account (+)
            sleep(0.01)
            print("logout - go to main menu") # logout (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "SERIOUS:") # class SERIOUS: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "tim " + Fore.CYAN + "or " + Fore.WHITE + "time" + " - shows ryal time ") # tim (+)
            sleep(0.01)
            print("stopwatch - shows stopwatch") # stopwatch (+)
            sleep(0.01)
            print("timer - shows timer") # timer (+)
            sleep(0.01)
            print("calculator - shows calculator") # calculator (+)
            sleep(0.01)
            print("calendar - shows calendar") # calendar (+)
            sleep(0.01)
            print("webcam_recorder - shows webcam video recorder (without taking voice (you can use dictaphone for recording voice))") # webcam_recorder (+)
            sleep(0.01)
            print("screen_recorder - shows screen video recorder (without taking voice (you can use dictaphone for recording voice))") # screen_recorder (+) need add to c/c++
            sleep(0.01)
            print("cur_conv - shows currency converter") # cur_conv (+)
            sleep(0.01)
            print("notepad - shows notepad") # notepad (+)
            sleep(0.01)
            print("translator - shows languages translator") # translator (+)
            sleep(0.01)
            print("dictaphone - shows dictaphone") # dictaphone (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "GAMES:") # class GAMES: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "pacman - shows pacman") # pacman (+)
            sleep(0.01)
            print("2048 - shows 2048") # 2048 (+)
            sleep(0.01)
            print("arkanoid - shows arkanoid") # arkanoid (+)
            sleep(0.01)
            print("flappy_bird - shows flappy bird") # flappy_bird (+)
            sleep(0.01)
            print("tetris - shows tetris") # tetris (+)
            sleep(0.01)
            print("hangman - shows hangman") # hangman (+)
            sleep(0.01)
            print("car_racing - shows car racing game") # car_racing (+)
            sleep(0.01)
            print("guess_number - shows game guess my number") # guess_number (+)
            sleep(0.01)
            print("math_game - shows math game") # math_game (+)
            sleep(0.01)
            print("typing_tutor - shows typing tutor") # typing_tutor (+)
            sleep(0.01)
            print("battle_city - shows battle city") # battle_city (+)
            sleep(0.01)
            print("doom - shows doom") # doom (+)
            sleep(0.01)
            print("mario - shows mario") # mario (+)
            sleep(0.01)
            print("snake - shows snake game " + Fore.YELLOW + "(" + Fore.WHITE + " 1, 2, ai " + Fore.YELLOW + ")" + Fore.WHITE) # snake (+)
            sleep(0.01)
            print("ping_pong - shows ping pong " + Fore.YELLOW + "(" + Fore.WHITE + " 1, 2, ai " + Fore.YELLOW + ")" + Fore.WHITE) # ping_pong (+)
            sleep(0.01)
            print("tic_tac_toe - shows tic-tac-toe " + Fore.YELLOW + "(" + Fore.WHITE + " 2, ai " + Fore.YELLOW + ")" + Fore.WHITE) # tic_tac_toe (+)
            sleep(0.01)
            print("checkers - shows checkers " + Fore.YELLOW + "(" + Fore.WHITE + " 2, ai " + Fore.YELLOW + ")" + Fore.WHITE) # checkers (+)
            sleep(0.01)
            print("chess - shows chess " + Fore.YELLOW + "(" + Fore.WHITE + " 2, ai " + Fore.YELLOW + ")" + Fore.WHITE) # chess (+)
            sleep(0.01)
            print("space_shooter - shows space shooter ") # space shooter (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "OWNS:") # class OWNS: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "title - set input title " + Fore.YELLOW + "( " + Fore.WHITE + "title name" + Fore.YELLOW + " )" + Fore.WHITE) # title (+)
            sleep(0.01)
            print("new " + Fore.CYAN + "or " + Fore.WHITE + "start" + " - create new Dragon console ") # new (+)
            sleep(0.01)
            print("open - open entered path to file " + Fore.YELLOW + "( " + Fore.WHITE + "path" + Fore.YELLOW + " )" + Fore.WHITE) # open (+)
            sleep(0.01)
            print("shutdown - shutdown your laptop") # shutdown (+) 
            sleep(0.01)
            print("restart - restart your laptop") # restart (+)
            sleep(0.01)
            print("data - shows real time data") # data (+)
            sleep(0.01)
            print("i_am_here - shows time which you spent here") # i_am_here (+)
            sleep(0.01)
            print("&main - turn main " + Fore.YELLOW + "(" + Fore.WHITE + " on, off " + Fore.YELLOW + ")" + Fore.WHITE) # &main (+)
            sleep(0.01)
            print("donate - donate specified amount of money for author") # donate (+) need add to c/c++
            sleep(0.01)
            print("donators - shows list of top 15 donators for author (updating with new version)") # donators (+)
            sleep(0.01)
            print("helpers - shows list of top 15 helpers for author (updating with new version)") # helpers (+)
            sleep(0.01)

            color = Fore.WHITE + " color"
            koma = Fore.WHITE + ","
            g = Fore.GREEN + " g"
            b = Fore.BLUE + " b"
            r = Fore.RED + " r"
            y = Fore.YELLOW + " y"
            bl = Fore.WHITE + " bl"
            w = Fore.WHITE + " w"
            p = Fore.MAGENTA + " p"
            wb = Fore.CYAN + " wb "

            print("color - set color text " + Fore.YELLOW + "(" + Fore.WHITE + color + koma + g + koma + b + koma + r + koma + y + koma + bl + koma + w + koma + p + koma + wb + Fore.YELLOW + ")" + Fore.WHITE) # color (+)
            sleep(0.01)
            print("color_back - set color background console " + Fore.YELLOW + "(" + Fore.WHITE + color + koma + g + koma + b + koma + r + koma + y + koma + bl + koma + w + koma + p + koma + wb + Fore.YELLOW + ")" + Fore.WHITE) # color_back (+)
            sleep(0.01)
            print("i? - shows you are admin or user") # i? (+)
            sleep(0.01)
            print("administrator " + Fore.CYAN + "or " + Fore.WHITE + "admin " + Fore.CYAN + "or " + Fore.WHITE + "superuser" + " - open Dragon console as administrator") # administrator (+)
            sleep(0.01)
            print("chan_backg - set desktop background with entered path to photo " + Fore.YELLOW + "( " + Fore.WHITE + "path" + Fore.YELLOW + " )" + Fore.WHITE) # chan_backg (+)
            sleep(0.01)
            print("send_ph_message - send message on entered phone number") # send_ph_message (+)
            sleep(0.01)
            print("history - shows commands which you already wrote") # history (+)
            sleep(0.01)
            print("cls_history - clear commands which you already wrote") # cls_history (+)
            sleep(0.01)
            print("memory - shows memory of your disk") # memory (+)
            sleep(0.01)
            print("rules - shows rules of this console") # rules (+)
            sleep(0.01)
            print("commands - shows just commands") # commands (+)
            sleep(0.01)
            print("tips - shows just tips") # tips (+)
            sleep(0.01)
            print("links - shows just links") # links (+)
            sleep(0.01)
            print("dragon_helper - will enter commands by your saying while did not say 'exit'") # dargon_helper (+) need add to c/c++
            sleep(0.01)
            print("my_volume_level - shows windows volume level") # my_volume_level (+)
            sleep(0.01)
            print("set_volume_level - set windows volume level " + Fore.YELLOW + "( " + Fore.WHITE + "number" + Fore.YELLOW + " )" + Fore.WHITE) # set_volume_level (+)
            sleep(0.01)
            print("set_mute - set windows mute " + Fore.YELLOW + "(" + Fore.WHITE + " on, off " + Fore.YELLOW + ")" + Fore.WHITE) # set_mute (+)
            sleep(0.01)
            print("ip - shows your ip address") # ip (+)
            sleep(0.01)
            print("size - set console size with entered parameters " + Fore.YELLOW + "( " + Fore.WHITE + "x, y" + Fore.YELLOW + " )" + Fore.WHITE) # size (+)
            sleep(0.01)
            print("my_location - shows your location") # my_location (+)
            sleep(0.01)
            print("system_info - shows info about computer") # system_info (+)
            sleep(0.01)
            print("energy " + Fore.CYAN + "or " + Fore.WHITE + "power" + " - shows energy of computer " ) # energy (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "PRANKS:") # class PRANKS: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "prank_button - shows prank with run away button " + Fore.YELLOW + "(" + Fore.WHITE + " yes, no " + Fore.YELLOW + ")" + Fore.WHITE) # prank_button (+)
            sleep(0.01)
            print("melt_screen - shows melting screen, for exit click on console, press 'Esc'") # melt_screen (+)
            sleep(0.01)
            print("gdi_virus - shows gdi virus, for exit press 'Esc'") # gdi_virus (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.YELLOW + "ELSES:") # class ELSES: (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "exit " + Fore.CYAN + "or " + Fore.WHITE + "esc " + Fore.CYAN + "or " + Fore.WHITE + "quit" + " - exit from here ") # exit (+)
            sleep(0.01)
            imports.own.will_go_to_start.main()
