from msvcrt import getch
import imports.own.will_go_to_start
from colorama import Fore
import os
from time import sleep

def donators_start():

    os.system("cls")
    print(" ")
    print(Fore.RED + "                                                              Press 'Esc' for exit" + Fore.WHITE)
    sleep(0.01)
    print(Fore.YELLOW + "                                                                   DONATORS: " + Fore.WHITE)
    sleep(0.01)
    print(" ")
    sleep(0.01)
    print("                                                                 1) Cinderella - $10")
    sleep(0.01)
    print("                                                                 2) no body")
    sleep(0.01)
    print("                                                                 3) no body")
    sleep(0.01)
    print("                                                                 4) no body")
    sleep(0.01)
    print("                                                                 5) no body")
    sleep(0.01)
    print("                                                                 6) no body")
    sleep(0.01) 
    print("                                                                 7) no body")
    sleep(0.01)
    print("                                                                 8) no body")
    sleep(0.01)
    print("                                                                 9) no body")
    sleep(0.01)
    print("                                                                10) no body")
    sleep(0.01)
    print("                                                                11) no body")
    sleep(0.01) 
    print("                                                                12) no body")
    sleep(0.01)
    print("                                                                13) no body")
    sleep(0.01)
    print("                                                                14) no body")
    sleep(0.01) 
    print("                                                                15) no body")
    sleep(0.01)
    getch()
    imports.own.will_go_to_start.main()
