from time import sleep
from colorama import Fore
import imports.own.will_go_to_start

def links_start():
    
            print(" ")
            print("\033[0;31mLINKS: \033[0;37m \n") # class !MAIN LINKS! (+)
            sleep(0.01)
            print("1) " + Fore.YELLOW + "For social media: " + Fore.WHITE) # 1) For social media (+)
            sleep(0.01)
            print("2) YouTube: @Oxdan_Praduction /OR/ https://www.youtube.com/@Oxdan_Praduction ") # 1) link Youtube (+)
            sleep(0.01)
            print("3) Tiktok: @oxdan_praduction /OR/ https://www.tiktok.com/@oxdan_praduction ") # 1) link Tiktok (+)
            sleep(0.01)
            print("4) Instagram: @oxdanpraduction /OR/ https://instagram.com/oxdanpraduction ") # 1) link Instagram (+)
            sleep(0.01)
            print("5) Facebook: @Mariia Sierova /OR/ https://www.facebook.com/profile.php?id=100087125340188&mibextid=LQQJ4d ") # 1) link Facebook (+)
            sleep(0.01)
            print("6) Github: @Mester-Oxdan /OR/ https://github.com/Mester-Oxdan ") # 1) link Github (+)
            sleep(0.01)
            print("7) Thingiverse: https://www.thingiverse.com/oxdan_praduction/designs") # 1) link Thingiverse (+)
            sleep(0.01)
            print("8) " + Fore.YELLOW + "For Sponsoring/Donations: " + Fore.WHITE) # 1) Sponsoring/Donations (+)
            sleep(0.01)
            print("9) Cash App: $BoHladii /OR/ 4403 9352 3234 1307 ") # 1) link Cash App (+)
            sleep(0.01)
            print("10) Buy Me A Coffee: https://www.buymeacoffee.com/oxdan ") # 1) link Buy Me A Coffee (+)
            sleep(0.01)
            print("11) " + Fore.YELLOW + "For Shops: " + Fore.WHITE) # 1) For Shops (+)
            sleep(0.01)
            print("12) Etsy: https://oxdanpraduction3dart.etsy.com ") # 1) link Etsy (+)
            sleep(0.01)
            print("13) Tik Tok Shop: @oxdan_praduction_shop /OR/ https://www.tiktok.com/@oxdan_praduction_shop?_t=8p4TNukKU4w&_r=1 ") # 1) link Tik Tok Shop (+)
            sleep(0.01)
            print("14) Facebook Shop: https://www.facebook.com/profile.php?id=61558180556782&mibextid=kFxxJD ") # 1) link Facebook Shop (+)
            sleep(0.01)
            print("15) Shopify: https://933791-66.myshopify.com/ ") # 1) link Shopify (+)
            sleep(0.01)
            print("16) " + Fore.YELLOW + "For Other: " + Fore.WHITE) # 1) For Other (+)
            sleep(0.01)
            print("17) Website: https://oxdan.com ") # 1) link OXDAN Website (+)
            sleep(0.01)
            print("18) " + Fore.YELLOW + "Thanks: " + Fore.WHITE) # 1) Thanks (+)
            sleep(0.01)
            print("19) Chess.com: https://www.chess.com/home ") # 1) link Chess (+)
            sleep(0.01)
            print("20) Google Maps Locator: https://www.maps.ie/coordinates.html ") # 1) link Google Maps Locator (+)
            sleep(0.01)
            imports.own.will_go_to_start.main()
