from time import sleep
from colorama import Fore
import imports.own.will_go_to_start

def links_start():
    
            print(" ")
            print(Fore.RED + "LINKS:") # class !MAIN LINKS! (+)
            sleep(0.01)
            print(" ")
            sleep(0.01)
            print(Fore.WHITE + "1) OXDAN Website (https://oxdan.com)") # 1) link OXDAN (+)
            sleep(0.01)
            print("2) Chess.com (https://www.chess.com/home)") # 2) link chess.com (+)
            sleep(0.01)
            print("3) Google Maps Locator (https://www.maps.ie/coordinates.html)") # 3) link google maps locator (+)
            sleep(0.01)
            print("4) Github (https://github.com/Mester-Oxdan)") # 4) link Github (+)
            sleep(0.01)
            print("5) Youtube (https://www.youtube.com/@Oxdan_Praduction)") # 5) link Youtube (+)
            sleep(0.01)
            print("6) TikTok (https://www.tiktok.com/@oxdan_praduction)") # 6) link TikTok (+)
            sleep(0.01)
            print("7) Instagram (https://instagram.com/oxdanpraduction)") # 7) link Instagram (+)
            sleep(0.01)
            print("8) Kwork (https://kwork.com/user/jecob)") # 8) link Kwork (+)
            sleep(0.01)
            print("9) Fiverr (https://www.fiverr.com/jecob_567)") # 9) Fiverr (+)
            sleep(0.01)
            print("10) Upwork (https://www.upwork.com/freelancers/~01e296384cd379e73e?viewMode=1&mp_source=share)") # 10) Upwork (+)
            sleep(0.01)
            print("11) Reddit (https://www.reddit.com/u/detektive-void/s/JyYykvbe9o)") # 11) Reddit (+)
            sleep(0.01)
            print("12) For Sponsoring/Donations: Cash App ($BoHladii /OR/ 4403 9352 3234 1307)") # 12) Sponsoring/Donations Cash App (+)
            sleep(0.01)
            print("13) Buy Me A Coffee (https://www.buymeacoffee.com/oxdan)") # 13) Buy Me A Coffee (+)
            sleep(0.01)
            print("14) For Shops: Etsy (https://oxdanpraduction3dart.etsy.com)") # 14) Etsy (+)
            sleep(0.01)
            print("15) ") # 15)  (+)
            sleep(0.01)
            imports.own.will_go_to_start.main()
